name: QA

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm run test.ci
      - run: npm run build.ci
      - run: npm run build-lib
      - name: Publish
        working-directory: ./dist-lib
        run: npm publish --access public --tag ${{github.ref_name == 'master' && 'latest' || 'next' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
